### ISSUE TITLE
Active Support由来のメソッドが使用されている

### ISSUE THREAD

**Issue by KazutakaShiohara** [cuon-inc/zuora#1]
依存関係を少なくするため、Active Support由来のメソッドを使用しないようにしたい。
`#blank?`と`#squish`が対象。

**Comment by rakio1234** [comment]
@cuon-kakimoto 
active_support外すと普段使っているコードの書き方と異なることで保守しにくくなるデメリットがあるかと思いました。
また依存関係を少なくしたいとのことですがactive_supportのアップデートで何かコードが壊れるとかも考えにくいなと思います 🤔 
なので外さなくてもいいのではと思いましたがいいかがでしょう？

**Comment by cuon-kakimoto** [comment]
了解です。CLOSEしますね。
