### ISSUE TITLE
Action#queryの第2引数にRequest header情報を設定できるように変更

### ISSUE THREAD

**Issue by yuuta31** [cuon-inc/zuora#18]
## 概要
- Zuora::Api::V1::Action.queryメソッドの第2引数に、http requestのheaders情報を渡せるように修正
https://github.com/cuon-inc/zuora/blob/main/lib/zuora/api/v1/action.rb
最終的には以下行でheaderを統合
https://github.com/cuon-inc/zuora/blob/main/lib/zuora/api/v1/base.rb#L35
- Zuora::Core.whereメソッドの第3引数に、http requestのheaders情報を渡せるように修正
https://github.com/cuon-inc/zuora/blob/main/lib/zuora/core.rb
- Zuora::Subscription.whereメソッドの引数にhttp requestのheaders情報を渡せるように修正
https://github.com/cuon-inc/zuora/blob/main/lib/zuora/subscription.rb#L9

**Comment by cuon-ssuzuki** [comment]
gemの改修をしない方針となったため、クローズ。
