### ISSUE TITLE
first/lastのSQL実装

### ISSUE THREAD

**Issue by cuon-kakimoto** [cuon-inc/zuora#8]
* 対応

全取得のあとのorderのためデータ量が多くなると遅い。SQL実装とする

**Comment by rakio1234** [comment]
@cuon-kakimoto 

https://knowledgecenter.zuora.com/Central_Platform/Query/ZOQL
<img width="607" alt="スクリーンショット 2022-06-08 23 20 57" src="https://user-images.githubusercontent.com/6119100/172640509-b0bb32da-14a3-4e85-bd5a-a84a0f7e208d.png">

orderがsqlでサポートされていないので難しい気がしています 🙏 
他に何か良い方法あればいいのですが 調べても見つからなかったです  🙇

**Comment by cuon-kakimoto** [comment]
```
      records = Zuora::Api::V1::Action.query("select id, name, CreatedDate from Account")["records"]
      account_id = records.max_by { |h| h["CreatedDate"] }["Id"]
```
たとえば、group by CreatedDateでmax値をとることは可能なのでしょうか？
```
records = Zuora::Api::V1::Action.query("select max(id), max(CreatedDate) from Account group by CreatedDate")["records"]
```

これも難しければ、Coreへの実装のみでお願いします!
- [ ] Account#firstをCoreモデルに移植し、Core#first
- [ ] Core#lastを実装

追記)

sfdcのほうはorder使えるんですね。。。
```
      query = <<-QUERY.squish
        select Id
        from #{object_name}
        order by Id desc
        limit 1
      QUERY
```

**Comment by rakio1234** [comment]
試してみます !

**Comment by rakio1234** [comment]
遅くなってすみません。
色々試したのですが syntax errorとなって無理でした
あと集約関数もサポートされてないとありました 😓 
<img width="562" alt="スクリーンショット 2022-06-26 22 58 29" src="https://user-images.githubusercontent.com/6119100/175817928-720921d0-e9ef-4a53-b48e-654a731285a4.png">

なのでCoreへの実装だけやります 👍

**Comment by rakio1234** [comment]
https://knowledgecenter.zuora.com/Central_Platform/Query/Export_ZOQL
なんかexport zoqlってやつだと集計関数やorderもサポートされているぽいです
でも、csvファイルで出力されるみたいです 🤔
